<script src="{{ asset('assets/backend/js/core.js') }}"></script>
<script src="{{ asset('assets/backend/js/jquery-3.7.0.min.js') }}"></script>
<script src="{{ asset('assets/backend/js/flatpickr.min.js') }}"></script>
<script src="{{ asset('assets/backend/js/apexcharts.min.js') }}"></script>
<script src="{{ asset('assets/backend/js/feather.min.js') }}"></script>
<script src="{{ asset('assets/backend/js/template.js') }}"></script>
<script src="{{ asset('assets/backend/js/dashboard-light.js') }}"></script>
<script src="{{ asset('assets/backend/js/data-table.js') }}"></script>
<script src="{{ asset('assets/backend/js/select2.min.js') }}"></script>
<!-- <script src="{{ asset('assets/backend/js/select2.multi-checkboxes.js') }}"></script> -->
<script src="{{ asset('assets/backend/js/appPageEvents.js') }}"></script>
<script src="{{ asset('assets/backend/js/appFunctions.js') }}"></script>
<script src="{{ asset('assets/backend/js/form-validation.js') }}"></script>
<script src="{{ asset('assets/backend/js/bootstrap-maxlength.js') }}"></script>
<!-- <script src="{{ asset('assets/backend/js/select2.js') }}"></script> -->
<script src="{{ asset('assets/backend/js/typeahead.js') }}"></script>
<script src="{{ asset('assets/backend/js/tags-input.js') }}"></script>
<script src="{{ asset('assets/backend/js/dropzone.js') }}"></script>
<script src="{{ asset('assets/backend/js/dropify.js') }}"></script>
<script src="{{ asset('assets/backend/js/flatpickr.js') }}"></script>
<script src="{{ asset('assets/backend/js/upload-image.js') }}"></script>
<script src="{{ asset('assets/backend/js/sortable.min.js') }}"></script>
<script src="{{ asset('assets/backend/js/toastr.js') }}"></script>
<script src="{{ asset('assets/backend/js/multiselect-dropdown.js') }}"></script>
<!-- <script src="{{ asset('assets/backend/js/jquery.repeater.min.js') }}"></script> -->
<script src="{{ asset('assets/backend/js/autoNumeric.min.js') }}"></script>
<script src="{{ asset('assets/backend/js/bootstrap-colorpicker.min.js') }}"></script>
<script src="{{ asset('assets/backend/js/browser-image-compression.js') }}"></script>
<script src="{{ asset('assets/backend/js/daterangepicker.js') }}"></script>
<script src="{{ asset('assets/backend/js/pnotify.min.js') }}"></script>
<script src="{{ asset('assets/backend/js/uniform.min.js') }}"></script>
<!-- <script src="{{ asset('assets/backend/js/creatChildAttribute.js') }}"></script> -->

<script src="{{ asset('assets/backend/vendors/datatables.net/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/backend/vendors/datatables.net-bs5/dataTables.bootstrap5.js') }}"></script>
<script src="{{ asset('assets/backend/vendors/feather-icons/feather.min.js') }}"></script>
<script src="{{ asset('assets/backend/vendors/jquery-validation/jquery.validate.min.js') }}"></script>
<script src="{{ asset('assets/backend/vendors/bootstrap-maxlength/bootstrap-maxlength.min.js') }}"></script>
<script src="{{ asset('assets/backend/vendors/inputmask/jquery.inputmask.min.js') }}"></script>
<!-- <script src="{{ asset('assets/backend/vendors/select2/select2.min.js') }}"></script> -->
<script src="{{ asset('assets/backend/vendors/typeahead.js/typeahead.bundle.min.js') }}"></script>
<script src="{{ asset('assets/backend/vendors/jquery-tags-input/jquery.tagsinput.min.js') }}"></script>
<script src="{{ asset('assets/backend/vendors/dropzone/dropzone.min.js') }}"></script>
<script src="{{ asset('assets/backend/vendors/dropify/dropify.min.js') }}"></script>
<script src="{{ asset('assets/backend/vendors/moment/moment.min.js') }}"></script>
<script src="{{ asset('assets/backend/vendors/flatpickr/flatpickr.min.js') }}"></script>

<!-- Region APP -->
<script src="{{ asset('assets/backend/js/appFunctions.js') }}"></script>
<script src="{{ asset('assets/backend/js/appConsts.js') }}"></script>
<script src="{{ asset('assets/backend/js/appPageEvents.js') }}"></script>
<!-- Endregion APP -->